GLOBAL:
  EXPERIMENT_NAME: LAE
  USE_GPU: true
  RESUME: false
  RESUME_PATH: ./train_log/2022-0926_1009/checkpoints/best.pth
  DEVICE: '0' # 'cpu' or '0' or '0,1,2,3' ...
  EPOCH_NUM: 300
  SAVE_RESULT_DIR: ./train_log
  SAVE_EPOCH_STEP: 1
  VAL_EPOCH_STEP: 1
  PRETRAINED_MODEL:
  DISTRIBUTED: true
  EARLY_STOP_PATIENCE: 500000
  DATA_DIR: ./data
  VISUAL_AUGMENTATION: false
  USE_AMP: true

TRAIN:
  IMG_SIZE: 224
  TRANSFORMS_RANDOMHORIZONTALFLIP: true
  TRANSFORMS_RANDOMVERTIACALFLIP: true
  TRANSFORMS_COLORJITTER:
  TRANSFORMS_BRIGHTNESS: 0.1
  TRANSFORMS_CONTRAST: 0.1
  TRANSFORMS_SATURATION: 0.1
  TRANSFORMS_HUE: 0
  BATCHSIZE_PER_CARD: 64
  DROP_LAST: true
  NUM_WORKERS: 4

MODEL:
  NAME: LAE
  IN_CHANNEL: 784
  LATENT_DIM: 64

  # LAE's parameter
  LAE_ENCODER_HIDDEN_DIM: [512, 256, 128]
  LAE_DECODER_HIDDEN_DIM: [128, 256, 512]

  # VAE's parameter
  VAE_HIDDEN_DIM: [32, 64, 128, 256, 512]

CRITERION:
  NAME: MSE
  COORD_RATIO: 1
  CLASSIFIER_RATIO: 0.5

  # VAE's parameter
  KLD_WEIGHT: 0.00025

OPTIMIZER:
  NAME: Adam
  WEIGHT_DECAY: 0.0005
  EPSILON: 0.00000001
  MOMENTUM: 0.9
  NESTEROV: true
  LEARNING_RATE: 0.0001
  WARMUP_EPOCH: 5
  BETA1: 0.9
  BETA2: 0.999

SCHEDULER:
  NAME: multistep_lr

  LR_LRF: 0.2

  MULTI_STEP: [100, 150, 200, 250]
  MULTI_STEP_GAMMA: 0.5

  ONE_CYCLE_TYPE: linear
